### ISSUE TITLE
Add a new table containing references to Users and Posts tables to store bookmarked posts for each user

### ISSUE THREAD

**Issue by cathyxfeiyang** [CMU-313/spring24-nodebb-apple#1]
Links users to the posts they've bookmarked, migrate database
Effort: Medium
Dependencies: None
Acceptance criteria: dditional table in database to store bookmarked posts by each user, contains FKs of posts and users that links these tables to store users’ bookmarked posts

**Comment by Xeno852** [comment]
Reference #22
