### ISSUE TITLE
Implement logic to add, remove, and view all bookmarked posts

### ISSUE THREAD

**Issue by cathyxfeiyang** [CMU-313/spring24-nodebb-apple#2]
Utilize database techniques (CRUD operations) to add and remove bookmarks (adding / deleting a row in bookmarks table), and view all bookmarked posts (list all filter by userID)
Effort: medium
Dependencies: https://github.com/CMU-313/spring24-nodebb-apple/issues/1
Acceptance criteria: users can add / remove bookmarks to posts, and view all bookmarks

**Comment by cathyxfeiyang** [comment]
https://github.com/CMU-313/spring24-nodebb-apple/issues/1

**Comment by Xeno852** [comment]
Reference #22
