### ISSUE TITLE
Add anonymous posting option to topic and post creation UI

### ISSUE THREAD

**Issue by cathyxfeiyang** [CMU-313/spring24-nodebb-apple#34]
- Implement toggle for users to select whether they want to create the topic or post anonymously
- Design and implement UI changes to add this toggle to the topic and post creation page

Effort: high
Dependencies: None

Acceptance criteria: 

- post and topics creation pages include a toggle for users to select anonymous posting
- manual testing for successful creation of anonymous posts and topics

**Comment by utkanuygur** [comment]
https://github.com/CMU-313/spring24-nodebb-apple/pull/60
